### ISSUE TITLE
Add Twitter link support

### ISSUE THREAD

**Issue by Nyazuma** [saucesteals/previewer-js#21]
If it could be possible to do the same for Twitter link.

**Comment by saucesteals** [comment]
Discord already automatically embeds twitter links (with special care even to include likes, followers, etc)
<img width="613" alt="image" src="https://user-images.githubusercontent.com/69014264/163190140-3bf7358f-c9fe-4876-920b-43e645155985.png">

**Comment by Nyazuma** [comment]
Yes they do but it is bugged. 
On desktop half the time the video crash when playing through the discord generated embed.
But most important on the mobile version there is no embed with the video for Twitter, idk why, we have to click the Twitter link to be redirected on Twitter and see the video.

**Comment by saucesteals** [comment]
> Yes they do but it is bugged. On desktop half the time the video crash when playing through the discord generated embed. But most important on the mobile version there is no embed with the video for Twitter, idk why, we have to click the Twitter link to be redirected on Twitter and see the video.

AFAIK the video "crashing" is a problem with the playback URL that Twitter gives out, so previewer embeds may run into the same exact problem (which I assume wouldn't be very hard to get around).

If twitter support was to be added to previewer, I think it would be necessary to also add support for preferences (ability to disable the different providers for each server)
